export const PLANS = [
  {
    id: 'basic',
    name: 'Monthly Tier',
    price: 200.0,
    months: 1,
    features: [
      'Premium Real-time tracking',
      'AIS140 support included',
      'Full Telemetry & Reports',
      'Mobile App & AI Insights',
      'Incl. GST, Server & Cloud',
    ],
    color: '#94a3b8',
  },
  {
    id: 'premium',
    name: 'Half-Yearly Tier',
    price: 1000.0,
    months: 6,
    features: [
      'Premium Real-time tracking',
      'AIS140 support included',
      'Full Telemetry & Reports',
      'Mobile App & AI Insights',
      'Incl. GST, Server & Cloud',
    ],
    color: '#3b82f6',
    popular: true,
  },
  {
    id: 'enterprise',
    name: 'Yearly Elite Tier',
    price: 2000.0,
    months: 12,
    features: [
      'Premium Real-time tracking',
      'AIS140 support included',
      'Full Telemetry & Reports',
      'Mobile App & AI Insights',
      'Incl. GST, Server & Cloud',
    ],
    color: '#8b5cf6',
  },
];
